name: CI

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: chatbot

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Retrieve version from package.json
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master

      - name: Docker build
        run: docker build -t $IMAGE_NAME .

      - name: Docker login
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Push to Dockerhub
        run: |
          FULL_IMAGE_NAME=$(${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.package-version.outputs.current-version }})

          docker tag $IMAGE_NAME $FULL_IMAGE_NAME
          docker push $FULL_IMAGE_NAME
