name: Deployment
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker Tag'
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Deployment
        uses: chrnorm/deployment-action@releases/v1
        id: deployment
        with:
          environment: production
          
      - name: Mark Deployment In-Progress
        uses: chrnorm/deployment-status@releases/v1
        with:
          state: "in_progress"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          
      - name: Trigger Rancher Upgrade
        uses: sekassel-research/actions-rancher-update@1.1.3
        with:
          rancher_url: ${{ secrets.RANCHER_URL }}
          rancher_access: ${{ secrets.RANCHER_ACCESS }}
          rancher_key: ${{ secrets.RANCHER_KEY }}
          project_id: 1a5
          stack_name: web
          service_name: chatbot
          docker_image: shotbowofficial/chatbot:${{ github.event.inputs.tag }}
      
      - name: Mark Deployment Successful
        if: success()
        uses: chrnorm/deployment-status@releases/v1
        with:
          state: "success"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          
      - name: Mark Deployment Failure
        if: failure()
        uses: chrnorm/deployment-status@releases/v1
        with:
          state: "failure"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
